# Generated by Django 4.2.6 on 2023-10-13 00:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=255)),
                ('period', models.CharField(max_length=255)),
                ('max_students', models.IntegerField()),
                ('workload', models.IntegerField()),
                ('fault_limit', models.IntegerField()),
                ('cover_image', models.ImageField(null=True, upload_to='./static/img')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('birth_date', models.DateField()),
                ('institution', models.CharField(max_length=255)),
                ('role', models.IntegerField(choices=[(1, 'Student'), (2, 'Professor')], default=1)),
                ('profile_picture', models.ImageField(null=True, upload_to='./static/img')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserClassroom',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('classroom_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.classroom')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user')),
            ],
        ),
        migrations.CreateModel(
            name='Frequency',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.BooleanField()),
                ('attest', models.FileField(null=True, upload_to='./static/files')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user_classroom_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.userclassroom')),
            ],
        ),
        migrations.AddField(
            model_name='classroom',
            name='professor_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user'),
        ),
    ]
